"""Isolated video pose-analysis jobs and their on-disk artifacts."""

from __future__ import annotations

import shutil
import threading
import uuid
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any

import cv2

from app.pose.engine import PoseEngine, PoseEngineError
from app.pose.renderer import draw_players
from app.pose.schemas import (
    FrameResult,
    JobInput,
    JobOutputs,
    JobRecord,
    JobStatus,
    JobSummary,
    PlayerResult,
    PoseError,
)


class PoseJobError(RuntimeError):
    """Stable, API-facing error raised by job management operations."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(message)


class PoseJobManager:
    """Run pose analysis in isolated directories with bounded concurrency.

    The model is created lazily when no engine is injected. This keeps gateway
    startup independent of optional Torch dependencies and a local checkpoint.
    ``run_sync`` is intentionally public for deterministic tests and command
    line workers; ``start`` launches the same processing in a daemon thread.
    """

    _ARTIFACTS = {
        "video": "annotated.mp4",
        "frames": "frames.jsonl",
        "summary": "summary.json",
        "input": "input.mp4",
    }

    def __init__(
        self,
        storage_dir: str | Path,
        engine: Any | None = None,
        *,
        engine_factory: Callable[[], Any] | None = None,
        max_concurrent_jobs: int = 1,
        keypoint_threshold: float = 0.5,
        renderer: Callable[..., Any] = draw_players,
    ) -> None:
        if max_concurrent_jobs < 1:
            raise ValueError("max_concurrent_jobs must be at least 1")
        if not 0 <= keypoint_threshold <= 1:
            raise ValueError("keypoint_threshold must be between 0 and 1")
        if engine is not None and engine_factory is not None:
            raise ValueError("provide engine or engine_factory, not both")

        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        self._engine = engine
        self._engine_factory = engine_factory
        self._renderer = renderer
        self._keypoint_threshold = float(keypoint_threshold)
        self._slots = threading.BoundedSemaphore(max_concurrent_jobs)
        self._records: dict[str, JobRecord] = {}
        self._lock = threading.RLock()

    def _new_id(self) -> str:
        return f"pose-{uuid.uuid4().hex}"

    def _job_dir(self, job_id: str) -> Path:
        # IDs are generated by this manager. Keep this check for callers that
        # pass an externally obtained ID to artifact_path/get.
        if not job_id or Path(job_id).name != job_id or any(part in job_id for part in ("/", "\\")):
            raise PoseJobError("not_found", "Pose job was not found")
        return self.storage_dir / job_id

    def _record_path(self, job_id: str) -> Path:
        return self._job_dir(job_id) / "job.json"

    def _persist(self, record: JobRecord) -> None:
        path = self._record_path(record.job_id)
        path.write_text(record.model_dump_json(indent=2), encoding="utf-8")

    @staticmethod
    def _probe_video(path: Path) -> tuple[float, int]:
        capture = cv2.VideoCapture(str(path))
        try:
            if not capture.isOpened():
                raise PoseJobError("decode_error", "Unable to open uploaded video")
            fps = float(capture.get(cv2.CAP_PROP_FPS))
            frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
            if fps <= 0:
                fps = 30.0
            if frame_count < 1:
                raise PoseJobError("decode_error", "Uploaded video contains no readable frames")
            return fps, frame_count
        finally:
            capture.release()

    def create(self, source_path: str | Path, filename: str | None = None) -> JobRecord:
        """Copy an uploaded video into a new isolated job directory."""

        source = Path(source_path)
        if not source.is_file():
            raise PoseJobError("storage_error", "Uploaded video could not be read")

        job_id = self._new_id()
        directory = self._job_dir(job_id)
        input_path = directory / self._ARTIFACTS["input"]
        try:
            directory.mkdir(parents=True, exist_ok=False)
            if source.resolve() != input_path.resolve():
                shutil.copyfile(source, input_path)
            fps, frame_count = self._probe_video(input_path)
            input_name = Path(filename or source.name).name or "video.mp4"
            record = JobRecord(
                job_id=job_id,
                status=JobStatus.queued,
                progress=0.0,
                input=JobInput(
                    filename=input_name,
                    duration_ms=max(0, round(frame_count / fps * 1000)),
                    fps=fps,
                ),
            )
            with self._lock:
                self._records[job_id] = record
                self._persist(record)
            return record.model_copy(deep=True)
        except PoseJobError:
            shutil.rmtree(directory, ignore_errors=True)
            raise
        except (OSError, ValueError, cv2.error) as exc:
            shutil.rmtree(directory, ignore_errors=True)
            raise PoseJobError("storage_error", f"Unable to create pose job: {exc}") from exc

    def get(self, job_id: str) -> JobRecord:
        with self._lock:
            record = self._records.get(job_id)
            if record is None:
                raise PoseJobError("not_found", "Pose job was not found")
            return record.model_copy(deep=True)

    def artifact_path(self, job_id: str, artifact: str) -> Path:
        if artifact not in self._ARTIFACTS or artifact == "input":
            raise PoseJobError("not_found", "Pose artifact was not found")
        path = self._job_dir(job_id) / self._ARTIFACTS[artifact]
        with self._lock:
            if job_id not in self._records or not path.is_file():
                raise PoseJobError("not_found", "Pose artifact was not found")
        return path

    def _get_engine(self) -> Any:
        if self._engine is None:
            if self._engine_factory is not None:
                self._engine = self._engine_factory()
            else:
                self._engine = PoseEngine()
        return self._engine

    def _claim(self, job_id: str) -> None:
        if not self._slots.acquire(blocking=False):
            raise PoseJobError("busy", "The pose analysis worker is busy")
        try:
            with self._lock:
                record = self._records.get(job_id)
                if record is None:
                    raise PoseJobError("not_found", "Pose job was not found")
                if record.status is not JobStatus.queued:
                    raise PoseJobError("invalid_state", "Pose job has already started")
                record.status = JobStatus.running
                record.progress = 0.0
                self._persist(record)
        except Exception:
            self._slots.release()
            raise

    def start(self, job_id: str) -> JobRecord:
        """Start a queued job in a daemon thread and return its running record."""

        self._claim(job_id)
        worker = threading.Thread(
            target=self._run_claimed,
            args=(job_id,),
            name=f"pose-job-{job_id}",
            daemon=True,
        )
        worker.start()
        return self.get(job_id)

    def run_sync(self, job_id: str) -> JobRecord:
        """Run a queued job synchronously, primarily for tests and workers."""

        self._claim(job_id)
        self._run_claimed(job_id)
        return self.get(job_id)

    def _run_claimed(self, job_id: str) -> None:
        try:
            self._process(job_id)
        except PoseJobError as exc:
            self._fail(job_id, exc.code, exc.message)
        except PoseEngineError as exc:
            self._fail(job_id, exc.code, exc.message)
        except (OSError, cv2.error) as exc:
            self._fail(job_id, "storage_error", f"Pose artifact processing failed: {exc}")
        except Exception as exc:  # Keep failures stable at the API boundary.
            self._fail(job_id, "inference_error", f"Pose analysis failed: {exc}")
        finally:
            self._slots.release()

    def _fail(self, job_id: str, code: str, message: str) -> None:
        with self._lock:
            record = self._records.get(job_id)
            if record is None:
                return
            record.status = JobStatus.failed
            record.error = PoseError(code=code, message=message)
            record.outputs = JobOutputs()
            try:
                self._persist(record)
            except OSError:
                # There is no reliable place to persist a second failure.
                pass
        for artifact in ("video", "frames", "summary"):
            try:
                path = self._job_dir(job_id) / self._ARTIFACTS[artifact]
                path.unlink(missing_ok=True)
            except OSError:
                pass

    @staticmethod
    def _players(value: Sequence[Any]) -> list[PlayerResult]:
        players: list[PlayerResult] = []
        for item in value:
            players.append(item if isinstance(item, PlayerResult) else PlayerResult.model_validate(item))
        return players

    def _process(self, job_id: str) -> None:
        input_path = self._job_dir(job_id) / self._ARTIFACTS["input"]
        if not input_path.is_file():
            raise PoseJobError("decode_error", "Pose input video is missing")
        with self._lock:
            record = self._records[job_id]
            fps = record.input.fps
            expected_frames = max(1, round(record.input.duration_ms / 1000 * fps))

        capture = cv2.VideoCapture(str(input_path))
        writer: Any | None = None
        output_path = self._job_dir(job_id) / self._ARTIFACTS["video"]
        frames_path = self._job_dir(job_id) / self._ARTIFACTS["frames"]
        summary_path = self._job_dir(job_id) / self._ARTIFACTS["summary"]
        processed = 0
        player_max = 0
        confidence_sum = 0.0
        confidence_count = 0
        try:
            if not capture.isOpened():
                raise PoseJobError("decode_error", "Unable to open pose input video")
            width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
            if width < 1 or height < 1:
                raise PoseJobError("decode_error", "Video dimensions are invalid")
            writer = cv2.VideoWriter(
                str(output_path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height)
            )
            if not writer.isOpened():
                raise PoseJobError("storage_error", "Unable to create annotated video")

            engine = self._get_engine()
            with frames_path.open("w", encoding="utf-8") as frames_file:
                while True:
                    ok, frame = capture.read()
                    if not ok:
                        break
                    try:
                        players = self._players(engine.detect(frame))
                        annotated = self._renderer(
                            frame,
                            players,
                            threshold=self._keypoint_threshold,
                        )
                    except PoseEngineError as exc:
                        raise PoseJobError(exc.code, exc.message) from exc
                    except PoseJobError:
                        raise
                    except Exception as exc:
                        raise PoseJobError("inference_error", f"Pose inference failed: {exc}") from exc
                    frame_result = FrameResult(
                        frame_index=processed,
                        timestamp_ms=round(processed * 1000 / fps),
                        players=players,
                    )
                    frames_file.write(frame_result.model_dump_json() + "\n")
                    writer.write(annotated)
                    processed += 1
                    player_max = max(player_max, len(players))
                    confidence_sum += sum(player.score for player in players)
                    confidence_count += len(players)
                    with self._lock:
                        record = self._records[job_id]
                        record.progress = min(0.99, processed / expected_frames)

            if processed < 1:
                raise PoseJobError("decode_error", "Uploaded video contains no readable frames")
            summary = JobSummary(
                frame_count=processed,
                player_count_max=player_max,
                avg_confidence=(confidence_sum / confidence_count if confidence_count else 0.0),
            )
            summary_path.write_text(summary.model_dump_json(indent=2), encoding="utf-8")
            with self._lock:
                record = self._records[job_id]
                record.status = JobStatus.succeeded
                record.progress = 1.0
                record.summary = summary
                record.error = None
                record.outputs = JobOutputs(
                    video_url=self._ARTIFACTS["video"],
                    frames_url=self._ARTIFACTS["frames"],
                    summary_url=self._ARTIFACTS["summary"],
                )
                self._persist(record)
        finally:
            capture.release()
            if writer is not None:
                writer.release()


__all__ = ["PoseJobError", "PoseJobManager"]
